# Generated by Django 5.1 on 2024-09-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_post_options_remove_post_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
