# Generated by Django 5.1 on 2024-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrestaurant',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=200),
        ),
    ]
