# Generated by Django 5.1 on 2024-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactrestaurant_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrestaurant',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
