# Generated by Django 5.1 on 2024-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactrestaurant_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrestaurant',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
