# Generated by Django 5.1 on 2024-09-02 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookatable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookatable',
            name='guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
