# Generated by Django 5.1 on 2024-09-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookatable_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
