# Generated by Django 5.1 on 2024-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookatable_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
