# Generated by Django 5.1 on 2024-09-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bookatable_options_alter_bookatable_guests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookatable',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='bookatable',
            name='unique_booking_per_user_per_time',
        ),
    ]
